### ISSUE TITLE
significant digits in labels in the bucket view

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#100]
http://suave-dev.sdsc.edu/main/file=public_SDG_Indicators.csv&views=111010&view=bucket

select SDGI rank. These are integers. So we don't need to add two decimal places.

Also, let's figure out why it shows only three buckets in this case. Number of buckets varies by variable, and not clear how to control it.

**Comment by liside** [comment]
Added a check block in bucketview. Not sure if solves the problem completely.
