### ISSUE TITLE
Slider keeps selection after Clear All

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#102]
slider doesn't update selection in the breadcrumb:

http://suave-dev.sdsc.edu/main/file=public_SDG_Indicators.csv&views=111010&view=bucket
 - show distribution by Poverty, below 1.90: move the left slider handle to the right
 - clicking either local Clear, or Clear All results in breadcrumb still showing the selection

**Comment by izaslavsky** [comment]
It seems that it works for integers (no decimal values == no rounding?) but doesn't work for values with decimals.
For example, works for SDGI Rank, but doesn't work for SDGI Score. Need to fix that asap because this is the bulk of SDG indicators

**Comment by izaslavsky** [comment]
Ok, it is not that the values are integers or decimals, it seems. select "8 Child labor.." - this is a variable with decimals, but apparently bucket intervals are computed as integers. So it works. If interval boundaries are float, then it breaks (eg see "8 Empl to Pop ratio")

HOWEVER: if there is a text in "search variables", then it doesn't work for "8 Child labor" either. Interesting.

**Comment by liside** [comment]
Fixed by adding additional helper function. seems like there is a bug with Jquery UI slider.

**Comment by izaslavsky** [comment]
still one remaining issue here: 
http://suave-dev.sdsc.edu/main/file=public_SDG_Indicators.csv&views=111010&view=bucket

* show distribution by 1 Poverty, below 1.90: move the left slider handle to the right
* also subset by 2 Obesity also move the left slider handle to the right

(snapshot is http://suave-dev.sdsc.edu/snapshot/5885635c11f1220dcadca99b)

* clear 2 Obesity by clicking the red circle next to it
* clear 1 Pverty byy clicking the red circle next to it

you see that the filter on 2 Obesity reappears.

**Comment by izaslavsky** [comment]
One other minor thing, in the same application:
1) type in "child" in "search variables
2) move left slider bar to the right, to filter on "8 Child labor.."
3) Click the red circle next to  8 Child labor to remove this filter.
4) see that the breadcrumb now says "4 Primary school enrolled.."

this only happens when there was text typed in the "search variables" window

**Comment by liside** [comment]
try again now?

**Comment by liside** [comment]
just fixed it

**Comment by izaslavsky** [comment]
WONDERFUL! All works. Thank you!
