### ISSUE TITLE
when a new account created - notify Suave manager

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#108]
on new account - send email to zaslavsk@sdsc.edu or suave@sdsc.edu (which in turn would forward to emails of development team)

Possibly; automatically respond with a "Welcome" email ("thank you for registering...etc.)

**Comment by liside** [comment]
Do you have anything in mind to put in "welcome email"? or just "welcome" is enough?

**Comment by ghost** [comment]
updated email on account creation (only one paragraph changed).

Dear <Name>
 
Thank you for creating a SuAVE account. Here are some resources to help you get started:
 
1)      Publishing your datasets in SuAVE is straightforward. Once you login, click “New Survey”, enter a survey title, and point to a CSV file with the data. You can also customize the look and feel of the survey and add survey metadata – see a step-by-step guide at http://suave.sdsc.edu/tutorials/

2)      There is a large number of SuAVE applications under http://suave.sdsc.edu/gallery/ and http://suave.sdsc.edu/news/. Click “About Survey” on any application to learn more.

3)      You can illustrate your research with pointers to saved SuAVE views, using “Comment” and “Share” functions. As a result, readers will be able to reproduce your analysis, opening SuAVE at annotation points and tracing your steps, or take analysis in other directions. See an example at http://suave.sdsc.edu/blog/

Please don’t hesitate to email us with any questions about SuAVE. We’ll be happy to help. SuAVE project news are at http://suave.sdsc.edu/news. In addition to the current production version (suave-stage.sdsc.edu) you are also welcome to create an account on the development version (suave-dev.sdsc.edu), should you want to experiment with new features. 
 
Your feedback and suggestions are always welcome.
 
Thank you,
 
-        Ilya Zaslavsky, on behalf of the SuAVE team

**Comment by liside** [comment]
updated
