### ISSUE TITLE
Images of individual items don't show up in annotation

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#109]
see, for example, 
![image](https://cloud.githubusercontent.com/assets/2942656/22630186/eab03ae8-eba9-11e6-90b9-8b0ca47891d5.png)

**Comment by liside** [comment]
Is this a very old annotation? At the time, commenting on individual element has not been well supported.

**Comment by izaslavsky** [comment]
No, it's a couple days old,I.


Sent via the Samsung Galaxy S7, an AT&T 4G LTE smartphone
-------- Original message --------From: Side Li <notifications@github.com> Date: 2/5/17  6:06 PM  (GMT-08:00) To: liside/SuAVE <SuAVE@noreply.github.com> Cc: izaslavsky <ilya.zaslavsky@gmail.com>, Author <author@noreply.github.com> Subject: Re: [liside/SuAVE] Images of individual items don't show up in
  annotation (#109) 
Is this a very old annotation? At the time, commenting on individual element has not been well supported.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liside/SuAVE","title":"liside/SuAVE","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liside/SuAVE"}},"updates":{"snippets":[{"icon":"PERSON","message":"@liside in #109: Is this a very old annotation? At the time, commenting on individual element has not been well supported. "}],"action":{"name":"View Issue","url":"https://github.com/liside/SuAVE/issues/109#issuecomment-277571068"}}}

**Comment by liside** [comment]
It was made on "Fri Dec 02 2016 06:49:13 GMT+0000 (UTC)"
