### ISSUE TITLE
Advanced table editing doesn't work for long texts

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#111]
Try http://suave-dev.sdsc.edu/edit/zaslavsk/EC_Use_Cases.
Impossible to edit column names for long texts

**Comment by liside** [comment]
I think you can edit it. It's just hard to focus on the beginning of the cell

**Comment by liside** [comment]
By the way, I just tested. You can edit it

**Comment by izaslavsky** [comment]
maybe we try it over skype. I tried to remove parentheses from these column names: Main CI Challenges (list separated by line breaks)#long and Data Discovery Challenges (for DDH)#long

**Comment by liside** [comment]
Maybe we can skype during the weekend

**Comment by izaslavsky** [comment]
It will be difficult over the weekend; i'll be traveling. Perhaps Sunday afternoon/evening. Today should also work. It would be great to have the bugs fixed and a new version deployed by 2/23 (see http://blogs.loc.gov/inside_adams/2017/02/launching-a-data-revolution-ilya-zaslavsky-ph-d-speaking-on-february-23/)

**Comment by liside** [comment]
seems to work

**Comment by ghost** [comment]
I think need to re-open. I can see the heading text, but can't edit
