### ISSUE TITLE
Cannot assign #long

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#112]
in the same dataset, in Edit Variables, trying to set "Use case filename" as #long 
But #long doesn't show up in the list of options

**Comment by liside** [comment]
I can't reproduce the problem

**Comment by izaslavsky** [comment]
maybe we can try it over skype. Here is the list I am shown when trying to add another variable:
![image](https://cloud.githubusercontent.com/assets/2942656/23024343/b8f0221c-f40e-11e6-8b6e-94c9d3922fde.png)

**Comment by liside** [comment]
seems to work
