### ISSUE TITLE
Verified bug: accuracy 124%

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#115]
![image](https://cloud.githubusercontent.com/assets/2942656/23007898/85cd1b2c-f3c0-11e6-9e1b-f0b2b22b5efb.png)

I mentioned this earlier on slack. I just reproduced it.

**Comment by liside** [comment]
can you give me the snapshot URL so that I can reproduce this bug as well?

**Comment by izaslavsky** [comment]
This is a bit more complicated, snapshot doesn't capture it. Here is the sequence:
1) Show "3 Subj wellbeeing" as a slider on the left, and also as the sort variable  - in the bucket view.
2) Right-mouse-click on the slider, and set a new break point splitting the variable in two groups: one with 74 items, the second with 71 items (the break point is at 5.2227998.... also need to deal with excessive accuracy here.)
3) then filter on the three other variables:
first on "4 literacy" (see the range on the picture)
second on "3 physicians": first drag the slider a little, then drag it back
third on "6 improved sanitation.." (see the range on the picture)
4) then click "more info" to show the rule

It may be possible to reproduce it with less steps - but this is what i used

**Comment by liside** [comment]
fixed
