### ISSUE TITLE
wrong values on slidebar - coming from a different variable, most likely

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#117]
http://suave-dev.sdsc.edu/main/file=zaslavsk_General_Social_Survey__2010_Subset.csv&views=111000&view=grid

1) bucket view
2) search for highest year of school completed - move a slider to subset
3) then search respondents income - move a slider
4) search again for highest year of school completed - now it shows a different slider with different values 

![image](https://cloud.githubusercontent.com/assets/2942656/23147218/221b7e18-f792-11e6-847b-3fc752576dc7.png)

**Comment by liside** [comment]
I don't see the problem.

**Comment by liside** [comment]
oh, i see

**Comment by izaslavsky** [comment]
see the values under the slider: they are 1 never .. 4 often
Highest year of school completed should be like 0-20

**Comment by liside** [comment]
fixed
