### ISSUE TITLE
Google analytics and/or Wordpress analytics module for suave.sdsc.edu

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#58]

**Comment by izaslavsky** [comment]
there is a wordpress plugin
also google analytics on maxim

have it such that we know hits to individual surveys, and can summarize by user accounts

we would then email users every month how many hits they get on their published surveys, and also we'd need to have an overall summary 

http://stackoverflow.com/questions/4667068/how-to-measure-a-time-spent-on-a-page 

Google analytics should be just fine

**Comment by liside** [comment]
added on 3001 and wordpress
