### ISSUE TITLE
Sorting and selection in paged facets

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#64]
http://suave.sdsc.edu:3001/main/file=zaslavsk_Fish_Gallery_from_Florida_MNH.csv&views=111000&view=grid
- switch to bucket view
- subset to "Florida Keys" under Location (#long)
- sort by quantity (or by A-Z) It won't sort. 
- check several items under "Common name" , eg all items that have 5 or more - these are from several pages. Checking doesn't work consistently

Also see some CSS issues in Firefox (view icons disappear)

**Comment by liside** [comment]
resolved
