### ISSUE TITLE
when changing zoom level with modal window on, the window closes, and the app is stuck

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#65]
http://suave.sdsc.edu:3001/main/file=zaslavsk_General_Social_Survey__2010_Subset.csv&views=111000&view=grid
do our "general happiness" exercise, then click "more info"
then do CTRL +  to make the fonts bigger
the modal window disappears, but the app remains grayed out

**Comment by liside** [comment]
The problem is caused by old customized bootstrap library in SuAVE. It will take very long time to update it to newest version, so I chose to add several more lines of codes to handle this situation in particular.

**Comment by liside** [comment]
Now, if rule table is open while users zoom in/out, table will be closed automatically and background will be reset
