### ISSUE TITLE
Search in a paged facet only searches first page

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#70]
See http://suave.sdsc.edu:3001/main/file=zaslavsk_UCSD_Doctors.csv&views=111000&view=grid
Goto Languages Spoken
Under Search Values, start typing "Russian" - this works Ok because Russian happened to be on the first page.
However, when you want to select "Mandarin", or "Chinese" - nothing comes up because these languages are on other pages. Only when you switch to the second page and then start typing Mandarin then it works.

**Comment by liside** [comment]
resolved
