### ISSUE TITLE
mapping works incorrectly in 3001

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#72]
Compare http://suave.sdsc.edu:3000/snapshot/581a374adca3054378447433 and http://suave.sdsc.edu:3001/snapshot/581a37680f6c3a17fbb7e2e7 

in 3001, it doesn't show date and number variables correctly

**Comment by izaslavsky** [comment]
The fix broke another map:
http://suave.sdsc.edu:3001/main/file=zaslavsk_SDG_Indicators.csv&views=111010&view=grid
switch to map, select "SDGI rank" to map - it won't work.

I guess we need to test everything again before I can send out the newsletter.
Could you fix and test?

**Comment by liside** [comment]
fixed the additional problem. Testing now

**Comment by izaslavsky** [comment]
http://suave.sdsc.edu:3001/main/file=zaslavsk_SDG_Indicators.csv&views=111010&view=grid
now SDGI_Score doesn't work, though SDGI_Rank works

**Comment by liside** [comment]
The above problem was caused by floating point. Fixed now.

**Comment by liside** [comment]
let me test it more with #number tags
