### ISSUE TITLE
Something wrong in bucket view

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#78]
http://suave.sdsc.edu:3001/main/file=zaslavsk_Mexico_Health_and_Sanitation.csv&views=111000&view=grid
try to select "4.  Describe your health" in bucket view - it doesn't show the distribution.

**Comment by ghost** [comment]
it is an issue with #ordinal variables.
Same story in http://suave.sdsc.edu:3001/main/file=zaslavsk_American_National_Election_Survey_Pilot_2016.csv&views=111000&view=grid,
and show "likely to give money to an organization concerned with political and social"

**Comment by ghost** [comment]
seems like the same error as in issye 72
