### ISSUE TITLE
Selection in a paged filter doesn't work when selecting from more than one page

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#83]
http://suave.sdsc.edu:3001/main/file=zaslavsk_EarthCube_Members_2013.csv&views=111000&view=grid
expand "Primary domain", check "Cyberinfrastructure"
then go to the second page, and try to check another value. It won't work.

Also, unchecking it (clicking the red dot) will still keep "cyberinfrastructure" checked, though all items will be shown

**Comment by liside** [comment]
fixed
