### ISSUE TITLE
Slider for number variable type doesn't update correctly on selection or off selection

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE-Server#99]
http://suave-dev.sdsc.edu/main/file=zaslavsk_Webinar_20170111_Complete.csv&views=111010&view=bucket

1) select any country, eg Italy
2) expand "Session time (minutes)" - it shows between 51 and 98 mins (this is correct for Italy)
3) Click "Clear All" - the slider now shows more values, but a) it keeps the previous range of values (it should show from 1 to 100 instead), and b) it shows that the slider is filtered on. Both behaviors are incorrect.

4) on another reload from server - and now displaying the slider first, and then subsetting on Country - there is a different behavior. First the slider shows from 1 to 100 (this is correct). Then select Italy - and the slider still shows from 1 to 100. However, if should show 51 to 98.

**Comment by liside** [comment]
Updated. Please test

**Comment by izaslavsky** [comment]
Great! it works, thank you.
